### ISSUE TITLE
Migrate Registry Exhibits item health (missing items) report

### ISSUE THREAD

**Issue by christinklez** [ucldc/exhibitapp#39]
https://registry.cdlib.org/exhibitions/item_health/

**Comment by amywieliczka** [comment]
@christinklez this is updated!

**Comment by christinklez** [comment]
Thanks @amywieliczka! The one missing published item--that has yet to be harvested! (We have a request out to UCSF to recreate some objects in Nuxeo, for this particular collection.)

I know the custom crops/thumbnails have yet to be migrated. Should we expect to see these in the report?

**Comment by christinklez** [comment]
Discussed during stand-up that for custom objects, all the metadata and information is present! So these are not "missing." Thanks!
